name = "carleson"
defaultTargets = ["Carleson"]

[leanOptions]
relaxedAutoImplicit = false
pp.unicode.fun = true
autoImplicit = false
# This has lots of false positives currently.
linter.style.longLine = false
linter.oldObtain = true
linter.refine = true
linter.style.multiGoal = true
linter.flexible = true

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "5269898d6a51d047931107c8d72d934d8d5d3753"

[[require]]
name = "checkdecls"
git = "https://github.com/PatrickMassot/checkdecls.git"
rev = "1325b44da2cac7abb16b175128e589c780e4cc7e"

[[lean_lib]]
name = "Carleson"
moreLeanArgs = ["-Dpp.unicode.fun=true", "-DautoImplicit=false", "-DrelaxedAutoImplicit=false"]
